namespace SteamFleet.Contracts.Enums;

public enum AuditEventType
{
    LoginSucceeded,
    LoginFailed,
    SecretRead,
    SecretUpdated,
    AccountCreated,
    AccountUpdated,
    AccountArchived,
    PasswordChanged,
    SessionsDeauthorized,
    FamilyParentAssigned,
    FamilyParentRemoved,
    FamilySynced,
    FamilyInviteSent,
    FamilyInviteAccepted,
    FamilyInviteFailed,
    ExternalFamilyMemberUpserted,
    GamesRefreshed,
    FriendInviteSynced,
    FriendInviteAccepted,
    FriendConnectFailed,
    RiskSignalDetected,
    RiskCooldownScheduled,
    RiskRecovered,
    SensitiveReportDownloaded,
    JobCreated,
    JobStarted,
    JobCompleted,
    JobCanceled,
    JobItemFailed,
    SystemError
}
